/* This SAS program was automatically generated by Stat/Transfer ver.13.3.984.0312 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'C:/Users/wb355347/Desktop/Findex/data/sassyntax/micro_world.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'C:/Users/wb355347/Desktop/Findex/data/sassyntax/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = micro_wo ;

proc format library = library ;
   value WP1219F
      1 = 'Male'  
      2 = 'Female' ;
   value AGE
      15 = '15'  
      16 = '16'  
      17 = '17'  
      18 = '18'  
      19 = '19'  
      20 = '20'  
      21 = '21'  
      22 = '22'  
      23 = '23'  
      24 = '24'  
      25 = '25'  
      26 = '26'  
      27 = '27'  
      28 = '28'  
      29 = '29'  
      30 = '30'  
      31 = '31'  
      32 = '32'  
      33 = '33'  
      34 = '34'  
      35 = '35'  
      36 = '36'  
      37 = '37'  
      38 = '38'  
      39 = '39'  
      40 = '40'  
      41 = '41'  
      42 = '42'  
      43 = '43'  
      44 = '44'  
      45 = '45'  
      46 = '46'  
      47 = '47'  
      48 = '48'  
      49 = '49'  
      50 = '50'  
      51 = '51'  
      52 = '52'  
      53 = '53'  
      54 = '54'  
      55 = '55'  
      56 = '56'  
      57 = '57'  
      58 = '58'  
      59 = '59'  
      60 = '60'  
      61 = '61'  
      62 = '62'  
      63 = '63'  
      64 = '64'  
      65 = '65'  
      66 = '66'  
      67 = '67'  
      68 = '68'  
      69 = '69'  
      70 = '70'  
      71 = '71'  
      72 = '72'  
      73 = '73'  
      74 = '74'  
      75 = '75'  
      76 = '76'  
      77 = '77'  
      78 = '78'  
      79 = '79'  
      80 = '80'  
      81 = '81'  
      82 = '82'  
      83 = '83'  
      84 = '84'  
      85 = '85'  
      86 = '86'  
      87 = '87'  
      88 = '88'  
      89 = '89'  
      90 = '90'  
      91 = '91'  
      92 = '92'  
      93 = '93'  
      94 = '94'  
      95 = '95'  
      96 = '96'  
      97 = '97'  
      98 = '98'  
      99 = '99+' ;
   value EDUC
      1 = 'completed primary or less'  
      2 = 'secondary'  
      3 = 'completed tertiary or more'  
      4 = '(dk)'  
      5 = '(rf)' ;
   value INCOME_5F
      1 = 'Poorest 20%'  
      2 = 'Second 20%'  
      3 = 'Middle 20%'  
      4 = 'Fourth 20%'  
      5 = 'Richest 20%' ;
   value EMP_IN
      0 = 'out of workforce'  
      1 = 'in workforce' ;
   value YNDKRF
      1 = 'yes'  
      2 = 'no'  
      3 = '(dk)'  
      4 = '(ref)' ;
   value FIN14C
      1 = 'Pay online'  
      2 = 'In cash'  
      3 = '(dk)'  
      4 = '(ref)' ;
   value FIN24F
      1 = 'Possible'  
      2 = 'Not possible'  
      3 = '(dk)'  
      4 = '(ref)' ;
   value FIN25F
      1 = 'Main source: Savings'  
      2 = 'Main source: Family or friends'  
      3 = 'Main source: Money from working'  
      4 = 'Main source: Borrowing from a bank, empoyer, or private lender'  
      5 = 'Main source: Selling assets'  
      6 = 'Main source: Some other source'  
      7 = '(dk)'  
      8 = 'ref' ;
   value WP19512F
      1 = 'Yes'  
      2 = 'No'  
      3 = '(DK)'  
      4 = '(Refused)' ;
   value WP19513F
      1 = 'Yes'  
      2 = 'No'  
      3 = '(DK)'  
      4 = '(Refused)' ;
   value WP19520F
      1 = 'Yes'  
      2 = 'No'  
      3 = '(DK)'  
      4 = '(Refused)' ;
   value WP19521F
      1 = 'Yes'  
      2 = 'No'  
      3 = '(DK)'  
      4 = '(Refused)' ;
   value YNDKRF2F
      1 = 'yes'  
      2 = 'no'  
      3 = 'dk/ref' ;
   value RECEIVE_WAGES
      1 = 'into an account'  
      2 = 'Main source: Family or friends'  
      3 = 'Main source: Money from working'  
      4 = 'Main source: Borrowing from a bank, empoyer, or private lender'  
      5 = 'Main source: Selling assets'  
      6 = 'Main source: Some other source'  
      7 = '(dk)'  
      8 = 'ref' ;
   value YESNO
      0 = 'no/dk/ref'  
      1 = 'yes' ;

DATA library.&dataset ;
INFILE datafile LRECL=215;
INPUT
   economy $ 1-24           economycode $ 25-27      regionwb $ 28-77      
   pop_adult  78-89         wpid_random  90-98       wgt  99-115           
   female  116              age  117-118             educ  119             
   inc_q  120               emp_in  121              fin2  122             
   fin3  123                fin4  124                fin5  125             
   fin6  126                fin7  127                fin8  128             
   fin9  129                fin10  130               fin11a  131           
   fin11b  132              fin11c  133              fin11d  134           
   fin11e  135              fin11f  136              fin11g  137           
   fin11h  138              fin14a  139              fin14b  140           
   fin14c  141              fin15  142               fin16  143            
   fin17a  144              fin17b  145              fin19  146            
   fin20  147               fin21  148               fin22a  149           
   fin22b  150              fin22c  151              fin24  152            
   fin25  153               fin26  154               fin27a  155           
   fin27b  156              fin27c1  157             fin27c2  158          
   fin28  159               fin29a  160              fin29b  161           
   fin29c1  162             fin29c2  163             fin30  164            
   fin31a  165              fin31b  166              fin31c  167           
   fin32  168               fin33  169               fin34a  170           
   fin34b  171              fin34c1  172             fin34c2  173          
   fin35  174               fin36  175               fin37  176            
   fin38  177               fin39a  178              fin39b  179           
   fin39c1  180             fin39c2  181             fin40  182            
   fin41  183               fin42  184               fin43a  185           
   fin43b  186              fin43c1  187             fin43c2  188          
   fin44  189               fin45  190               fin46  191            
   fin47a  192              fin47b  193              fin47c1  194          
   fin47c2  195             fin47c3  196             fin47c4  197          
   fin47c5  198             mobileowner  199         fin48  200            
   account_fin  201         account_mob  202         account  203          
   saved  204               borrowed  205            receive_wages  206    
   receive_transfers  207   receive_pension  208     receive_agriculture  209
   pay_utilities  210       remittances  211         pay_onlne  212        
   pay_onlne_mobintbuy  213   pay_cash  214            pay_cash_mobintbuy  215
 ;                       

LABEL
   economy = "Economy"
   economycode = "Economy Code"
   regionwb = "Region, WB"
   pop_adult = "Population 15+, 2016, WDI"
   wpid_random = "Gallup World Poll identifier"
   wgt = "Weight"
   female = "Respondent is female"
   age = "Respondent age"
   educ = "Respondent education level"
   inc_q = "Within-economy household income quintile"
   emp_in = "Respondent is in the workforce"
   fin2 = "Has a debit card"
   fin3 = "If has debit card: card in own name"
   fin4 = "If has debit card: used card in past 12 months"
   fin5 = "Used mobile phone or internet to access FI account"
   fin6 = "Used mobile phone or internet to check account balance"
   fin7 = "Has a credit card"
   fin8 = "If has credit card: used card in past 12 months"
   fin9 = "If has account: any deposit into account in past 12 months"
   fin10 = "If has account: any withdrawal from account in past 12 months"
   fin11a = "If does not have account: b/c too far away"
   fin11b = "If does not have account: b/c too expensive"
   fin11c = "If does not have account: b/c lack documentation"
   fin11d = "If does not have account: b/c lack trust"
   fin11e = "If does not have account: b/c religious reasons"
   fin11f = "If does not have account: b/c lack of money"
   fin11g = "If does not have account: b/c family member already has one"
   fin11h = "If does not have account: b/c no need for financial services"
   fin14a = "Made bill payments online using the Internet"
   fin14b = "Bought something online using the Internet"
   fin14c = "Paid online or in cash at delivery"
   fin15 = "Saved in past 12 months: for farm/business purposes"
   fin16 = "Saved in past 12 months: for old age"
   fin17a = "Saved in past 12 months: using an account at a financial institution"
   fin17b = "Saved in past 12 months: using an informal savings club"
   fin19 = "Has loan from a financial institution for home, apartment, or land"
   fin20 = "Borrowed in past 12 months: for medical purposes"
   fin21 = "Borrowed in past 12 months: for farm/business purposes"
   fin22a = "Borrowed in past 12 months: from a financial institution"
   fin22b = "Borrowed in past 12 months: from family or friends"
   fin22c = "Borrowed in past 12 months: from an informal savings club"
   fin24 = "Possibility of coming up with emergency funds"
   fin25 = "Main source of emergency funds"
   fin26 = "Sent domestic remittances in past 12 months"
   fin27a = "If sent domestic remittances: through a financial institution"
   fin27b = "If sent domestic remittances: through a mobile phone"
   fin27c1 = "If sent domestic remittances: in cash"
   fin27c2 = "If sent domestic remittances: through an MTO"
   fin28 = "Received domestic remittances in past 12 months"
   fin29a = "If received domestic remittances: through a financial institution"
   fin29b = "If received domestic remittances: through a mobile phone"
   fin29c1 = "If received domestic remittances: in cash"
   fin29c2 = "If received domestic remittances: through an MTO"
   fin30 = "Paid utility bills in past 12 months"
   fin31a = "If paid utility bills: using an account"
   fin31b = "If paid utility bills: through a mobile phone"
   fin31c = "If paid utility bills: in cash"
   fin32 = "Received wage payments in past 12 months"
   fin33 = "If received wage payments: work in public sector"
   fin34a = "If received wage payments: into an account"
   fin34b = "If received wage payments: through a mobile phone"
   fin34c1 = "If received wage payments: in cash"
   fin34c2 = "If received wage payments: to a card"
   fin35 = "If received cashless wage payments: first account"
   fin36 = "If received cashless wage payments: opened to receive payments"
   fin37 = "Received government transfers in past 12 months"
   fin38 = "Received government transfers in past 12 months: pension"
   fin39a = "If received government transfers: into an account"
   fin39b = "If received government transfers: through a mobile phone"
   fin39c1 = "If received government transfers: in cash"
   fin39c2 = "If received government transfers: to a card"
   fin40 = "If received cashless government transfers: first account"
   fin41 = "If received cashless government transfers: opened to receive payments"
   fin42 = "Received agricultural payments in past 12 months"
   fin43a = "If received agricultural payments: into an account"
   fin43b = "If received agricultural payments: through a mobile phone"
   fin43c1 = "If received agricultural payments: in cash"
   fin43c2 = "If received agricultural payments: to a card"
   fin44 = "If received agricultural payments: opened to receive payments"
   fin45 = "If received agricultural payments: opened to receive payments"
   fin46 = "Received self-employment payments: in past 12 months"
   fin47a = "If received self-employment payments: into an account"
   fin47b = "If received self-employment payments: through a mobile phone"
   fin47c1 = "If received self-employment payments: in cash"
   fin47c2 = "If received self-employment payments: to a card"
   fin47c3 = "Marginal: Used debit card in your own name"
   fin47c4 = "Marginal: Used mobile phone or internet to access FI account"
   fin47c5 = "Marginal: Used mobile phone or internet to check account balance"
   mobileowner = "Owns a mobile phone"
   fin48 = "Has a national ID"
   account_fin = "Has an account at a financial institution"
   account_mob = "Has a mobile money account"
   account = "Has an account"
   saved = "Saved in the past year"
   borrowed = "Borrowed in the past year"
   receive_wages = "Payments: wage payments"
   receive_transfers = "Payments: government transfers"
   receive_pension = "Payments: government pension"
   receive_agriculture = "Payments: selling agricultural goods"
   pay_utilities = "Payments: utility bills"
   remittances = "Domestic remittances"
   pay_onlne = "Pay online [of adults]- F2F"
   pay_onlne_mobintbuy = "Pay online [of buyers]- F2F"
   pay_cash = "Pay in cash when order is delivered [of adults]- F2F"
   pay_cash_mobintbuy = "Pay in cash when order is delivered [of buyers]- F2F" ;

FORMAT
   female WP1219F.          age AGE.                 educ EDUC.            
   inc_q INCOME_5F.         emp_in EMP_IN.           fin2 YNDKRF.          
   fin3 YNDKRF.             fin4 YNDKRF.             fin5 YNDKRF.          
   fin6 YNDKRF.             fin7 YNDKRF.             fin8 YNDKRF.          
   fin9 YNDKRF.             fin10 YNDKRF.            fin11a YNDKRF.        
   fin11b YNDKRF.           fin11c YNDKRF.           fin11d YNDKRF.        
   fin11e YNDKRF.           fin11f YNDKRF.           fin11g YNDKRF.        
   fin11h YNDKRF.           fin14a YNDKRF.           fin14b YNDKRF.        
   fin14c FIN14C.           fin15 YNDKRF.            fin16 YNDKRF.         
   fin17a YNDKRF.           fin17b YNDKRF.           fin19 YNDKRF.         
   fin20 YNDKRF.            fin21 YNDKRF.            fin22a YNDKRF.        
   fin22b YNDKRF.           fin22c YNDKRF.           fin24 FIN24F.         
   fin25 FIN25F.            fin26 YNDKRF.            fin27a YNDKRF.        
   fin27b YNDKRF.           fin27c1 YNDKRF.          fin27c2 YNDKRF.       
   fin28 YNDKRF.            fin29a YNDKRF.           fin29b YNDKRF.        
   fin29c1 YNDKRF.          fin29c2 YNDKRF.          fin30 YNDKRF.         
   fin31a YNDKRF.           fin31b YNDKRF.           fin31c YNDKRF.        
   fin32 YNDKRF.            fin33 YNDKRF.            fin34a YNDKRF.        
   fin34b YNDKRF.           fin34c1 YNDKRF.          fin34c2 YNDKRF.       
   fin35 WP19512F.          fin36 WP19513F.          fin37 YNDKRF.         
   fin38 YNDKRF.            fin39a YNDKRF.           fin39b YNDKRF.        
   fin39c1 YNDKRF.          fin39c2 YNDKRF.          fin40 WP19520F.       
   fin41 WP19521F.          fin42 YNDKRF.            fin43a YNDKRF.        
   fin43b YNDKRF.           fin43c1 YNDKRF.          fin43c2 YNDKRF.       
   fin44 YNDKRF.            fin45 YNDKRF.            fin46 YNDKRF.         
   fin47a YNDKRF.           fin47b YNDKRF.           fin47c1 YNDKRF.       
   fin47c2 YNDKRF.          fin47c3 YNDKRF.          fin47c4 YNDKRF.       
   fin47c5 YNDKRF.          mobileowner YNDKRF.      fin48 YNDKRF.         
   account_fin YNDKRF2F.    account_mob YNDKRF2F.    account YNDKRF2F.     
   saved YNDKRF2F.          borrowed YNDKRF2F.       receive_wages RECEIVE_WAGES.
   pay_onlne YESNO.         pay_onlne_mobintbuy YESNO.   pay_cash YESNO.       
   pay_cash_mobintbuy YESNO. ;


LENGTH
   wpid_random 6            female 3                 age 3                 
   educ 3                   inc_q 3                  emp_in 3              
   fin2 3                   fin3 3                   fin4 3                
   fin5 3                   fin6 3                   fin7 3                
   fin8 3                   fin9 3                   fin10 3               
   fin11a 3                 fin11b 3                 fin11c 3              
   fin11d 3                 fin11e 3                 fin11f 3              
   fin11g 3                 fin11h 3                 fin14a 3              
   fin14b 3                 fin14c 3                 fin15 3               
   fin16 3                  fin17a 3                 fin17b 3              
   fin19 3                  fin20 3                  fin21 3               
   fin22a 3                 fin22b 3                 fin22c 3              
   fin24 3                  fin25 3                  fin26 3               
   fin27a 3                 fin27b 3                 fin27c1 3             
   fin27c2 3                fin28 3                  fin29a 3              
   fin29b 3                 fin29c1 3                fin29c2 3             
   fin30 3                  fin31a 3                 fin31b 3              
   fin31c 3                 fin32 3                  fin33 3               
   fin34a 3                 fin34b 3                 fin34c1 3             
   fin34c2 3                fin35 3                  fin36 3               
   fin37 3                  fin38 3                  fin39a 3              
   fin39b 3                 fin39c1 3                fin39c2 3             
   fin40 3                  fin41 3                  fin42 3               
   fin43a 3                 fin43b 3                 fin43c1 3             
   fin43c2 3                fin44 3                  fin45 3               
   fin46 3                  fin47a 3                 fin47b 3              
   fin47c1 3                fin47c2 3                fin47c3 3             
   fin47c4 3                fin47c5 3                mobileowner 3         
   fin48 3                  account_fin 3            account_mob 3         
   account 3                saved 3                  borrowed 3            
   receive_wages 3          receive_transfers 3      receive_pension 3     
   receive_agriculture 3    pay_utilities 3          remittances 3         
   pay_onlne 3              pay_onlne_mobintbuy 3    pay_cash 3            
   pay_cash_mobintbuy 3 ;



RUN ;
